-- Oracle SQL Handbook 2026 - Chapitre 1

CREATE TABLE customers (
    customer_id   NUMBER GENERATED BY DEFAULT AS IDENTITY,
    customer_name VARCHAR2(100) NOT NULL,
    city          VARCHAR2(80),
    CONSTRAINT pk_customers PRIMARY KEY (customer_id)
);

CREATE TABLE orders (
    order_id    NUMBER GENERATED BY DEFAULT AS IDENTITY,
    customer_id NUMBER NOT NULL,
    order_date  DATE DEFAULT SYSDATE NOT NULL,
    amount      NUMBER(10,2) CHECK (amount >= 0),
    CONSTRAINT pk_orders PRIMARY KEY (order_id),
    CONSTRAINT fk_orders_customer FOREIGN KEY (customer_id)
        REFERENCES customers(customer_id)
);
